name: "Bug report"
description: "Signaler un dysfonctionnement dans Laravel Hotel"
title: "[BUG] : "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Merci de détailler le problème pour que l'équipe puisse le reproduire rapidement.
  - type: input
    id: summary
    attributes:
      label: Résumé
      description: "Une phrase pour décrire le bug"
      placeholder: "Impossible de confirmer une réservation après paiement"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Étapes de reproduction
      description: "Liste détaillée des actions à suivre pour reproduire le bug"
      placeholder: |
        1. Aller sur /reservations
        2. Cliquer sur Nouvelle réservation
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      placeholder: "La réservation est confirmée et un email est envoyé."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportement observé
      placeholder: "L'application affiche une erreur 500."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / captures d'écran
      description: "Collez les erreurs pertinentes ou joignez des captures d'écran."
      render: shell
  - type: input
    id: version
    attributes:
      label: Version / environnement
      description: "Branch, tag ou commit, ainsi que l'environnement (dev, staging, prod)."
      placeholder: "develop @ 3f4c1a8 – staging"
    validations:
      required: true
  - type: dropdown
    id: regression
    attributes:
      label: Est-ce une régression ?
      options:
        - "Je ne sais pas"
        - "Oui, récent"
        - "Non, bug ancien"
