name: "Bug report"
description: "Signaler un dysfonctionnement reproductible"
title: "[BUG] Résumé court"
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Fournissez assez de détails pour que l'équipe puisse reproduire et diagnostiquer rapidement.
  - type: input
    id: summary
    attributes:
      label: Résumé
      description: "Une phrase qui décrit le bug."
      placeholder: "Impossible de confirmer une réservation après paiement"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Étapes de reproduction
      description: "Listez chaque étape, avec l’URL concernée et les données utilisées le cas échéant."
      placeholder: |
        1. Aller sur /reservations
        2. Cliquer sur « Nouvelle réservation »
        3. Valider avec le client X
        4. …
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      placeholder: "La réservation est confirmée et un email est envoyé."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportement observé
      placeholder: "L'application affiche une erreur 500."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / captures d'écran
      description: "Ajoutez les erreurs pertinentes (stack trace, console, réseau) ou des captures."
      render: shell
  - type: input
    id: env
    attributes:
      label: Version / environnement
      description: "Branch, tag ou commit + environnement (dev, staging, prod)."
      placeholder: "develop @ 3f4c1a8 – staging"
    validations:
      required: true
  - type: dropdown
    id: regression
    attributes:
      label: Est-ce une régression ?
      options:
        - "Je ne sais pas"
        - "Oui"
        - "Non"
