name: "Feature request"
description: "Proposer une nouvelle fonctionnalité ou une amélioration majeure"
title: "[FEAT] Résumé du besoin"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Expliquez le besoin métier avant de proposer une solution technique. Des exemples réels aident à prioriser.
  - type: input
    id: summary
    attributes:
      label: Résumé
      placeholder: "Gestion des codes promo pour les réservations"
    validations:
      required: true
  - type: textarea
    id: business_need
    attributes:
      label: Besoin métier
      description: "Quel problème utilisateur ou opérationnel essayons-nous de résoudre ?"
      placeholder: "L'équipe marketing doit offrir des remises ciblées sans manipulation manuelle du calendrier."
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critères d’acceptation
      description: "Liste de scénarios qui doivent réussir pour considérer la fonctionnalité terminée."
      placeholder: |
        - Je peux créer un code promo avec un montant fixe ou un pourcentage.
        - Un client ne peut l'utiliser qu'une fois.
        - L'historique des codes utilisés apparaît dans la fiche réservation.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Pistes / contraintes
      description: "Idées techniques, contraintes connues ou impacts UI/API (optionnel)."
  - type: textarea
    id: notes
    attributes:
      label: Notes complémentaires
      description: "Liens, métriques, estimation, dépendances, etc. (optionnel)."
