name: "Task"
description: "Petite tâche technique ou opérationnelle"
title: "[TASK] Résumé court"
labels:
  - chore
body:
  - type: input
    id: summary
    attributes:
      label: Résumé
      placeholder: "Mettre à jour la configuration Reverb en staging"
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Détails / portée
      description: "Ce qu’il faut faire, avec l’environnement ou le service concerné."
  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      description: "Sous-tâches ou points de contrôle."
      placeholder: |
        - [ ] Étape 1
        - [ ] Étape 2
  - type: textarea
    id: done
    attributes:
      label: Définition de done
      description: "Comment saura-t-on que la tâche est terminée ?"
      placeholder: "Ex: Reverb répond OK en staging et les logs sont propres."
  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      options:
        - P0 – Urgent
        - P1 – Haute
        - P2 – Normale
        - P3 – Basse
