name: Security Checks

on:
  schedule: [{ cron: "0 6 * * 1" }] # chaque lundi 06:00 UTC
  workflow_dispatch:

jobs:
  composer-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
      - run: composer install --no-interaction --prefer-dist --no-progress
      - run: composer audit --no-dev --format=json | tee composer-audit.json
      - uses: actions/upload-artifact@v4
        with:
          name: composer-audit
          path: composer-audit.json
