name: Static Security Checks

on:
  pull_request:
    branches: [main, develop]

concurrency:
  group: static-security-${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  sast:
    name: Semgrep & Gitleaks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep (OWASP + Laravel)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/owasp-top-ten,p/php"
          generate-sarif: true
          sarif: semgrep.sarif

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-banner
